### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'name'

### ISSUE THREAD

**Issue by 1ntegrale9** [DiscordBotPortalJP/discord-manager#16]
エラー内容

```
2020-09-29T18:05:02.983059+00:00 app[discordbot.1]: Ignoring exception in on_message
2020-09-29T18:05:02.983350+00:00 app[discordbot.1]: Traceback (most recent call last):
2020-09-29T18:05:02.983665+00:00 app[discordbot.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/discord/client.py", line 312, in _run_event
2020-09-29T18:05:02.983667+00:00 app[discordbot.1]:     await coro(*args, **kwargs)
2020-09-29T18:05:02.983894+00:00 app[discordbot.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/Daug/cogs/thread.py", line 154, in on_message
2020-09-29T18:05:02.983896+00:00 app[discordbot.1]:     if self.is_category_closed(channel):
2020-09-29T18:05:02.987561+00:00 app[discordbot.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/Daug/cogs/thread.py", line 71, in is_category_closed
2020-09-29T18:05:02.987562+00:00 app[discordbot.1]:     if '✅' in channel.category.name:
2020-09-29T18:05:02.987642+00:00 app[discordbot.1]: AttributeError: 'NoneType' object has no attribute 'name'
```

**Comment by 1ntegrale9** [comment]
fixed
